### ISSUE TITLE
form ricostruzione

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentroitalia-heroku-php#13]
@Pinzauti ho aggiunto questo con una sezione ricostruzione.html e ricostruzione.php. il problema è che quando inserisco una segnalazione la label che ho definito non viene assegnata ma viene assegnata la "Non definito". che cosa sbaglio? https://terremotocentroitalia.herokuapp.com/segnalazioni/ricostruzione.html

**Comment by Pinzauti** [comment]
C'era da modificare anche lo script.js!
